spring.application.name=table editor

# Database configuration
spring.datasource.url=jdbc:mariadb://localhost:3306/db
spring.datasource.username=root
spring.datasource.password=db
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
